#!/usr/bin/env python

import rospy
import sys

from comp0037_obstacler.obstacler_node import ObstaclerNode

if __name__ == '__main__':
    try:
	# Strip out all the ROS-specific command line arguments
        obstaclerNode = ObstaclerNode()
        obstaclerNode.run()
    except rospy.ROSInterruptException:
        pass
